### ISSUE TITLE
Campos obligatorios que faltan

### ISSUE THREAD

**Issue by Lainezz** [abrahamr110/Gestion-de-Entrenamientos-Personales#1]
Recuerda que en el README deben aparecer los siguientes campos:
a.
Nombre del proyecto
b.
Idea del proyecto
c.
Justificación del proyecto
d.
Descripción detallada de las tablas que intervendrán en el proyecto

Mucho ánimo!

**Comment by abrahamr110** [comment]
Creo que ahora está bien.
